### ISSUE TITLE
vi mode no highlighting if bg transparent 

### ISSUE THREAD

**Issue by Parilia** [f4z3r/gruvbox-material.nvim#10]
Highlighting does not work with transparent background while in visual mode, No highlighting is shown and works fine if the background is not transparent.

**Comment by f4z3r** [comment]
Thanks for reporting this. Should be fixed in version 0.1.3:
![image](https://github.com/f4z3r/gruvbox-material.nvim/assets/32326425/e7946c6a-81c0-4bf1-be25-fe20c208d7a2)

Other backgrounds are now also applied, e.g. for floating windows:
![image](https://github.com/f4z3r/gruvbox-material.nvim/assets/32326425/29fba68f-6f3d-49fc-89be-18f181491f27)

Let me know if you still encounter issues elsewhere.
