### ISSUE TITLE
[BUG] Cannot set contrast when `vim.o.background` is after lazy.nvim loader

### ISSUE THREAD

**Issue by zenshidev** [f4z3r/gruvbox-material.nvim#36]
### Description

When I have such setup:
```
require('init_lazy')
vim.opt.background = 'light'
```

Setting contrast doesnt work:
```
{
  "f4z3r/gruvbox-material.nvim",
  name = "gruvbox-material",
  lazy = false,
  priority = 1000,
  opts = {
    contrast = "hard",
  }
}
```

I can check it using `:Telescope highlights`. For example group `DiffText`, uses bg0 color which is `#f9f5d7` for hard contrast and `#fbf1c7` for medium contrast.

And this is what Telescope reports:
![obraz](https://github.com/user-attachments/assets/68431675-38d9-4fad-b2f2-e1e3ea9cff87)

This is happening, because setting `vim.o.background` causes a separate call to `gruvbox.setup()` - with empty options - which means default values will be used instead of options provided in plugin spec.

I am not sure about solution here (do we silence other .setup() calls? make config global?) but it would be nice to fix that since I feel like order of config options shouldnt really matter ...

### Screenshot

- [X] I have added a screenshot in the description.

### Expected behavior

Order of configuration options doesnt matter

### Configuration

```{
  "f4z3r/gruvbox-material.nvim",
  name = "gruvbox-material",
  lazy = false,
  priority = 1000,
  opts = {
    contrast = "hard",
  }
}```

**Comment by f4z3r** [comment]
Hi @zenshixd , thanks for reporting this issue. I am guessing the subsequent call to `setup` is caused by another plugin that checks whether the background changes?

Can you test whether it works based on the `feat/config-cache` branch? This should enable several calls to `setup` which only override configuration previously set if explicitly given in the argument. Hence calling `setup` with empty arguments several times in a row should have no effect on the used configuration.

**Comment by zenshidev** [comment]
>I am guessing the subsequent call to setup is caused by another plugin that checks whether the background changes?

No, this doesnt seem to be the case - or rather, I tested this on empty setup with just lazy.nvim and gruvbox-material colorscheme installed - and the issue was the same. Its either lazy.nvim doing something weird vim options or its neovim itself.

>Can you test whether it works based on the feat/config-cache branch?

Unfortunately still doesnt work, still order seem to matter: 
![obraz](https://github.com/user-attachments/assets/ffb7fc2b-10a4-439e-a593-d65ce30cbded)


Also to make sure I have correct version downloaded, from `:Lazy`:
![obraz](https://github.com/user-attachments/assets/908aa8f8-3f3e-4132-a261-5f19f28a7778)

**Comment by f4z3r** [comment]
Ok, I'm guessing the issue actually stems from the fact that you call `colorscheme gruvbox-material` somewhere in your config. This is not needed, I updated the `feat/config-cache` branch such that it should now retain the configuration initially set when having calls to `colorscheme gruvbox-material`. I am experiencing some tiny visual artifacts still on my personal setup when testing this on `lualine.nvim`, but this might be due to my personal setup and not the colorscheme itself.

Let me know if now works with the updated branch. It should have one more commit. If it does, I will merge into `master` and check regarding the visual artifacts at a later time. Since no one reported this as a bug and I did not actually change code that could possibly affect the things I am seeing, it is unlikely due to the plugin.

**Comment by zenshidev** [comment]
> I'm guessing the issue actually stems from the fact that you call colorscheme gruvbox-material somewhere in your config.

I mean ... still not really :D You can check yourself, it was something I was doing previously - but I removed it during testing since yea it seemed unneeded. https://github.com/search?q=repo%3Azenshixd%2Fneovim%20colorscheme&type=code

Anyways, new fix works! Now I always have hard contrast no matter the config order. Thanks!

**Comment by f4z3r** [comment]
Probably called by some plugin at some point. There are many plugins that do this. For instance plugins that automatically update dark/light setup. But nice if it works, then I will merge this into master and close this.
